# configs/base.yaml
# === Model & Tokenisation ===
model_name: bert-base-uncased
max_length: 128

# === Training ===
batch_size: 16
epochs: 5
lr: 2e-5
weight_decay: 0.01
warmup_ratio: 0.06
dropout: 0.1

# === Imbalance & Reproducibility ===
use_weighted_loss: true
oversample: true
seed: 42

# === Paths ===
train_path: data/train.csv
dev_path: data/dev.csv
test_path: data/test.csv
output_dir: runs/bert_regression
