# configs/base.yaml
# === Model & Tokenisation ===
model_name: bert-base-uncased
max_length: 128

# === Training ===
batch_size: 16
epochs: 5
lr: 2e-5
weight_decay: 0.01
warmup_ratio: 0.06
dropout: 0.1

# === Imbalance & Reproducibility ===
use_weighted_loss: true
oversample: false
seed: 42

# === Paths ===
train_path: data/train.csv
dev_path: data/dev.csv
test_path: data/test.csv
output_dir: runs/bert_regression

# === Optional: class mapping thresholds for reporting classification-style metrics ===
thresholds: [0.25, 0.50, 0.75]  # 4 bins: [0,.25), [.25,.50), [.50,.75), [.75,1]
